name: Build to Release

on:
  push:
  # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      if: github.event.inputs.logLevel == 'build' || github.event.inputs.logLevel == 'release' 
      run: cargo build --verbose

    - name: Run tests
      if: github.event.inputs.logLevel == 'test' 
      run: cargo test --verbose

    - name: Release
      if: github.event.inputs.logLevel == 'release'
      run: echo "RELEASE HIT"
