name: Create Diagram

# Triggers For Action
on:
  # IDK yet
  workflow_dispatch: {}
  # Triggers based with a push given (Updating and uploading.)
  push:
    # When There's a push to the DEV, branch
    branches: [ DEV ]

# Main Action
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Downloading This Repo?
      - uses: githubocto/repo-visualizer@0.9.1 # Downloading This Repo?
        with:
          output_file: 'Documentation/Images/repo-diagram.svg'
