name: Rust

on:
  push:
    branches: [ "DEV" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Run as:'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - build
        - release

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      if: github.event.inputs.logLevel == 'build' || github.event.inputs.logLevel == 'release' 
      run: cargo build --verbose

    - name: Run tests
      if: github.event.inputs.logLevel == 'test' 
      run: cargo test --verbose

    - name: Release
      if: github.event.inputs.logLevel == 'release'
      run: echo "RELEASE HIT"
